title: Lars Erik Storbukås
name: Lars Erik Storbukås
user_title: Developer @ Evry
email: larserik.storbukas@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: storbukas
linkedin_username: storbukas
facebook_username: storbukas

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sass-converter
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  sections:
    output: false
  projects:
    output: true
